;; please place actions in the app-crm-core-action.sch file !!!
;; please place shared configuration routing rules in the app-crm-core-configshare.sch file !!!

;; BM Drivers
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Corba BM Driver")(setBeanProperty b "ClassName" "com.redknee.app.crm.bundle.driver.CORBABMDriver")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.bundle.driver.CORBABMDriver.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "PM BM Driver")(setBeanProperty b "ClassName" "com.redknee.app.crm.bundle.driver.PMBMDriver")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.bundle.driver.PMBMDriver.))) (setBeanProperty b "Delegate" (let ((b (com.redknee.app.crm.bundle.driver.CORBABMDriver.))) b)) b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Logging BM Driver")(setBeanProperty b "ClassName" "com.redknee.app.crm.bundle.driver.LoggingBMDriver")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.bundle.driver.LoggingBMDriver.))) (setBeanProperty b "Delegate" (let ((b (com.redknee.app.crm.bundle.driver.PMBMDriver.))) (setBeanProperty b "Delegate" (let ((b (com.redknee.app.crm.bundle.driver.CORBABMDriver.))) b)) b)) b)) b)))

;; Value Calculators
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "User Input")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.UserInputValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.UserInputValueCalculator.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Constant Value")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.ConstantValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.ConstantValueCalculator.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Date Formatter")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.DateFormattingValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.))) (.add c (let ((b (com.redknee.framework.xhome.entity.EntityRole.))) b)) c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.DateFormattingValueCalculator.))) b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Date Parser")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.DateParsingValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.))) (.add c (let ((b (com.redknee.framework.xhome.entity.EntityRole.))) b)) c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.DateParsingValueCalculator.))) b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Currency Formatter")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.CurrencyFormattingValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.))) (.add c (let ((b (com.redknee.framework.xhome.entity.EntityRole.))) b)) c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.CurrencyFormattingValueCalculator.))) b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Property Value")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.PropertyBasedValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.))) (.add c (let ((b (com.redknee.framework.xhome.entity.EntityRole.))) b)) c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.PropertyBasedValueCalculator.))) (setBeanProperty b "Property" #null) b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Service Property")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.ServiceValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.))) (.add c (let ((b (com.redknee.framework.xhome.entity.EntityRole.))) b)) c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.ServiceValueCalculator.))) (setBeanProperty b "Property" #null) b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Auxiliary Service Property")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.AuxiliaryServiceValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.))) (.add c (let ((b (com.redknee.framework.xhome.entity.EntityRole.))) b)) c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.AuxiliaryServiceValueCalculator.))) (setBeanProperty b "Property" #null) b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Service Fee Property")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.ServiceFee2ValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.))) (.add c (let ((b (com.redknee.framework.xhome.entity.EntityRole.))) b)) c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.ServiceFee2ValueCalculator.))) (setBeanProperty b "Property" #null) b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Service Package Property")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.ServicePackagePropertyValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.))) (.add c (let ((b (com.redknee.framework.xhome.entity.EntityRole.))) b)) c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.ServicePackagePropertyValueCalculator.))) (setBeanProperty b "Property" #null) b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Service Package Fee Property")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.ServicePackageFeePropertyValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.))) (.add c (let ((b (com.redknee.framework.xhome.entity.EntityRole.))) b)) c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.ServicePackageFeePropertyValueCalculator.))) (setBeanProperty b "Property" #null) b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Bundle Profile Property")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.BundleProfilePropertyValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.))) (.add c (let ((b (com.redknee.framework.xhome.entity.EntityRole.))) b)) c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.BundleProfilePropertyValueCalculator.))) (setBeanProperty b "Property" #null) b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Bundle Fee Property")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.BundleFeePropertyValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.))) (.add c (let ((b (com.redknee.framework.xhome.entity.EntityRole.))) b)) c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.BundleFeePropertyValueCalculator.))) (setBeanProperty b "Property" #null) b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Transaction Property")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.TransactionValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.TransactionValueCalculator.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Collection")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.CollectionValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.CollectionValueCalculator.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Collection Formatting")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.CollectionFormattingValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.CollectionFormattingValueCalculator.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Context Key")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.ContextObjectValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.ContextObjectValueCalculator.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Context Key Copy")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.ContextKeyCopyingValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.ContextKeyCopyingValueCalculator.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Current Date/Time")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.TimestampValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.))) (.add c (let ((b (com.redknee.framework.xhome.entity.EntityRole.))) b)) c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.TimestampValueCalculator.))) b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Random Number")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.RandomNumberValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.))) (.add c (let ((b (com.redknee.framework.xhome.entity.EntityRole.))) b)) c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.RandomNumberValueCalculator.))) b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Shell Script Value Calculator")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.ShellValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.ShellValueCalculator.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Mandatory Value Calculator")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.MandatoryValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.MandatoryValueCalculator.))) (setBeanProperty b "Delegate" #null) b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Default Value Calculator")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.DefaultValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.DefaultValueCalculator.))) (setBeanProperty b "Delegate" #null) b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Optional Element Value Calculator")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.OptionalElementValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.OptionalElementValueCalculator.))) (setBeanProperty b "Delegate" #null) b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "EmptyStringValueCalculator")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.EmptyStringValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.EmptyStringValueCalculator.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "ListValueCalculator")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.ListValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.ListValueCalculator.))) (setBeanProperty b "Delegate" #null)(setBeanProperty b "ListOfValueCalculators" (let ((c (java.util.ArrayList.)))  c)) b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "InternalKeyValueCalculator")(setBeanProperty b "ClassName" "com.redknee.app.crm.calculator.InternalKeyValueCalculator")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.calculator.InternalKeyValueCalculator.))) (setBeanProperty b "Delegate" #null) b)) b)))




;; SPID Extensions
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Subscription Notification")(setBeanProperty b "ClassName" "com.redknee.app.crm.extension.spid.NotificationMethodSpidExtension")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" #null) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "SAP Report")(setBeanProperty b "ClassName" "com.redknee.app.crm.extension.spid.SAPReportSpidExtension")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" #null) b)))


;; Service Extensions
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Alcatel SSC (Service Key/Value Pairs)")(setBeanProperty b "ClassName" "com.redknee.app.crm.extension.service.core.AlcatelSSCServiceExtension")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" #null) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "BlackBerry Services")(setBeanProperty b "ClassName" "com.redknee.app.crm.extension.service.core.BlackberryServiceExtension")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" #null) b)))

;; Auxiliary Services Extensions
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Additional MSISDN (Core)")(setBeanProperty b "ClassName" "com.redknee.app.crm.extension.auxiliaryservice.core.AddMsisdnAuxSvcExtension")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.extension.auxiliaryservice.core.AddMsisdnAuxSvcExtension.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Bolt-On Promotion (Core)")(setBeanProperty b "ClassName" "com.redknee.app.crm.extension.auxiliaryservice.core.URCSPromotionAuxSvcExtension")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.extension.auxiliaryservice.core.URCSPromotionAuxSvcExtension.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Discount")(setBeanProperty b "ClassName" "com.redknee.app.crm.extension.auxiliaryservice.core.DiscountAuxSvcExtension")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.extension.auxiliaryservice.core.DiscountAuxSvcExtension.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Gateway Service (Core)")(setBeanProperty b "ClassName" "com.redknee.app.crm.extension.auxiliaryservice.core.SPGAuxSvcExtension")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.extension.auxiliaryservice.core.SPGAuxSvcExtension.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Group Charging")(setBeanProperty b "ClassName" "com.redknee.app.crm.extension.auxiliaryservice.core.GroupChargingAuxSvcExtension")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.extension.auxiliaryservice.core.GroupChargingAuxSvcExtension.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Home Zone (Core)")(setBeanProperty b "ClassName" "com.redknee.app.crm.extension.auxiliaryservice.core.HomeZoneAuxSvcExtension")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.extension.auxiliaryservice.core.HomeZoneAuxSvcExtension.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Data Opt-In (Core)")(setBeanProperty b "ClassName" "com.redknee.app.crm.extension.auxiliaryservice.core.NGRCOptInAuxSvcExtension")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.extension.auxiliaryservice.core.NGRCOptInAuxSvcExtension.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Multi-SIM Charging (Core)")(setBeanProperty b "ClassName" "com.redknee.app.crm.extension.auxiliaryservice.core.MultiSimAuxSvcExtension")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.extension.auxiliaryservice.core.MultiSimAuxSvcExtension.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Personal Ring Back Tone (Core)")(setBeanProperty b "ClassName" "com.redknee.app.crm.extension.auxiliaryservice.core.PRBTAuxSvcExtension")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.extension.auxiliaryservice.core.PRBTAuxSvcExtension.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "PLP/CUG/BP (Core)")(setBeanProperty b "ClassName" "com.redknee.app.crm.extension.auxiliaryservice.core.CallingGroupAuxSvcExtension")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.extension.auxiliaryservice.core.CallingGroupAuxSvcExtension.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Provisionable")(setBeanProperty b "ClassName" "com.redknee.app.crm.extension.auxiliaryservice.core.ProvisionableAuxSvcExtension")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.extension.auxiliaryservice.core.ProvisionableAuxSvcExtension.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "VPN (Core)")(setBeanProperty b "ClassName" "com.redknee.app.crm.extension.auxiliaryservice.core.VPNAuxSvcExtension")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.extension.auxiliaryservice.core.VPNAuxSvcExtension.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Voicemail (Core)")(setBeanProperty b "ClassName" "com.redknee.app.crm.extension.auxiliaryservice.core.VoicemailAuxSvcExtension")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.extension.auxiliaryservice.core.VoicemailAuxSvcExtension.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Promotional SMS OPT_OUT (Core)")(setBeanProperty b "ClassName" "com.redknee.app.crm.extension.auxiliaryservice.core.PromOptOutAuxSvcExtension")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.extension.auxiliaryservice.core.PromOptOutAuxSvcExtension.)))  b)) b)))



;; Credit Category Extensions
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Late Fee")(setBeanProperty b "ClassName" "com.redknee.app.crm.extension.creditcategory.core.LateFeeCreditCategoryExtension")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" #null) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Early Reward")(setBeanProperty b "ClassName" "com.redknee.app.crm.extension.creditcategory.core.EarlyRewardCreditCategoryExtension")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" #null) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "Notice Schedule")(setBeanProperty b "ClassName" "com.redknee.app.crm.extension.creditcategory.NoticeScheduleCreditCategoryExtension")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" #null) b)))

;; System Status Dashboard Agent
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "SystemStatusDashboardAgent")(setBeanProperty b "ClassName" "com.redknee.app.crm.web.agent.SystemStatusDashboardAgent")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.web.agent.SystemStatusDashboardAgent.)))  b)) b)))

;; Predicates
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "IsGenericKeyConfiguration")(setBeanProperty b "ClassName" "com.redknee.app.crm.filter.IsGenericKeyConfigurationPredicate")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.filter.IsGenericKeyConfigurationPredicate.)))  b)) b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.xhome.entity.EntityInfoHome.class) (let ((b (com.redknee.framework.xhome.entity.EntityInfo.))) (setBeanProperty b "Name" "IsSystemDefinedKeyConfiguration")(setBeanProperty b "ClassName" "com.redknee.app.crm.filter.IsSystemDefinedKeyConfigurationPredicate")(setBeanProperty b "Roles" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Prototype" (let ((b (com.redknee.app.crm.filter.IsSystemDefinedKeyConfigurationPredicate.)))  b)) b)))
