;;
;; This journal file should contain all subscription related beans
;;

(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (bindHome ctx com.redknee.app.crm.bean.account.SubscriptionTypeHome.class com.redknee.app.crm.bean.account.SubscriptionType.class)))
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.account.SubscriptionTypeHome.class) (let ((b (com.redknee.app.crm.bean.account.SubscriptionType.))) (setBeanProperty b "Id" 10000L)(setBeanProperty b "Name" "Operator")(setBeanProperty b "Description" "Operator")(setBeanProperty b "Type" 31000) b))))
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.account.SubscriptionTypeHome.class) (let ((b (com.redknee.app.crm.bean.account.SubscriptionType.))) (setBeanProperty b "Id" 10001L)(setBeanProperty b "Name" "Mobile Airtime")(setBeanProperty b "Description" "Mobile Airtime")(setBeanProperty b "Type" 1) b))))
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.account.SubscriptionTypeHome.class) (let ((b (com.redknee.app.crm.bean.account.SubscriptionType.))) (setBeanProperty b "Id" 10002L)(setBeanProperty b "Name" "Mobile Wallet")(setBeanProperty b "Description" "Mobile Wallet")(setBeanProperty b "Type" 2) b))))
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.account.SubscriptionTypeHome.class) (let ((b (com.redknee.app.crm.bean.account.SubscriptionType.))) (setBeanProperty b "Id" 10003L)(setBeanProperty b "Name" "Network Wallet")(setBeanProperty b "Description" "Network Wallet")(setBeanProperty b "Type" 3) b))))
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.account.SubscriptionTypeHome.class) (let ((b (com.redknee.app.crm.bean.account.SubscriptionType.))) (setBeanProperty b "Id" 10004L)(setBeanProperty b "Name" "Prepaid Calling Card")(setBeanProperty b "Description" "Prepaid Calling Card Subscription Type")(setBeanProperty b "Type" 4) b))))
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.account.SubscriptionTypeHome.class) (let ((b (com.redknee.app.crm.bean.account.SubscriptionType.))) (setBeanProperty b "Id" 10005L)(setBeanProperty b "Name" "Wire Line")(setBeanProperty b "Description" "Wire Line Subscription Type")(setBeanProperty b "Type" 5) b))))
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.account.SubscriptionTypeHome.class) (let ((b (com.redknee.app.crm.bean.account.SubscriptionType.))) (setBeanProperty b "Id" 10006L)(setBeanProperty b "Name" "Broadband")(setBeanProperty b "Description" "Broadband Subscription Type")(setBeanProperty b "Type" 6) b))))



(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (bindHome ctx com.redknee.app.crm.bean.account.SubscriptionClassHome.class com.redknee.app.crm.bean.account.SubscriptionClass.class)))
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.account.SubscriptionClassHome.class) (let ((b (com.redknee.app.crm.bean.account.SubscriptionClass.))) (setBeanProperty b "Id" 1L)(setBeanProperty b "Name" "Mobile Airtime")(setBeanProperty b "Description" "airtime subscription")(setBeanProperty b "SubscriptionType" 10001L)(setBeanProperty b "SegmentType" 2) b))))
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.account.SubscriptionClassHome.class) (let ((b (com.redknee.app.crm.bean.account.SubscriptionClass.))) (setBeanProperty b "Id" 2L)(setBeanProperty b "Name" "Mobile Wallet")(setBeanProperty b "Description" "subscriber wallet")(setBeanProperty b "SubscriptionType" 10002L)(setBeanProperty b "TechnologyType" 31000)(setBeanProperty b "SegmentType" 1) b))))
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.account.SubscriptionClassHome.class) (let ((b (com.redknee.app.crm.bean.account.SubscriptionClass.))) (setBeanProperty b "Id" 3L)(setBeanProperty b "Name" "Network Wallet")(setBeanProperty b "Description" "wallet for vendors")(setBeanProperty b "SubscriptionType" 10003L)(setBeanProperty b "TechnologyType" 31000)(setBeanProperty b "SegmentType" 1) b))))
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.account.SubscriptionClassHome.class) (let ((b (com.redknee.app.crm.bean.account.SubscriptionClass.))) (setBeanProperty b "Id" 5L)(setBeanProperty b "Name" "Wire Line")(setBeanProperty b "Description" "Wire Line Subscription Class")(setBeanProperty b "SubscriptionType" 10005L)(setBeanProperty b "TechnologyType" 31000)(setBeanProperty b "SegmentType" 0) b))))
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.account.SubscriptionClassHome.class) (let ((b (com.redknee.app.crm.bean.account.SubscriptionClass.))) (setBeanProperty b "Id" 6L)(setBeanProperty b "Name" "Broadband")(setBeanProperty b "Description" "Broadband Subscription Class")(setBeanProperty b "SubscriptionType" 10006L)(setBeanProperty b "TechnologyType" 31000)(setBeanProperty b "SegmentType" 0) b))))

