(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "PREPAID_LICENSE_KEY")(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit")))  b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "RAsNCAYSEEhPU1RQXV9TUBBRTn9MTH0QAhMcT1JdWV4AEBBSEAwQDRANEAwOEEUQCwwECQsLCAkECg8MDgsPDw4OBRAQZXl3Y3lvcnl/dXBjeHV9bHlubA==") b)))

(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "POSTPAID_LICENSE_KEY")(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit")))  b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "LS4qJzMxaW5ydXF8fnJxMXBvXm1tXDEjMj1uc3x4fyExMXMxLTEsMSwxLS8xZDEqLSUoKiopKCUrLi0vKi4uLy8kMTFEWFZCWE5TWF5UUUJZVFxNSU5STQ==") b)))

(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "HYBRID_LICENSE_KEY")(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit")))  b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "JSYiLDg6YmV5fnp3dXl6OntkVWZmVzooOTZleHdzdCo6Ong6JjonOic6JiQ6bzohJi4jISEiIy4gJSYkISUlJCQvOjpPU11JU0VYU1VfWklSX0RUT14=") b)))

;; Install GSM technology license
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "GSM_FEATURE_LICENSE")(setBeanProperty b "Desc" "Provides access to the GSM technologies.")(setBeanProperty b "Offered" #t)(setBeanProperty b "Enabled" #f)(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit")))  b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "Qg0PDQAUFk5JVVJWW1lVVhZXSHlKSnsWBBUaSVRbX1gGFhZUFgoWCxYLFgoIFkMWDQoCDw0NDg8CDAkKCA0JCQgIAxYWf2l0f3lzdmV/aG9ue398ZXdpfQ==") b)))

;; Install TDMA and CDMA technology license
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "TDMA_CDMA_FEATURE_LICENSE")(setBeanProperty b "Desc" "Provides access to the TDMA and CDMA technologies.")(setBeanProperty b "Offered" #t)(setBeanProperty b "Enabled" #f)(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit")))  b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "XRwVFx8LCVFWSk1JREZKSQlIV2ZVVWQJGwoFVktEQEcZCQlLCRUJFAkUCRUXCVwJEhUdEBISERAdExYVFxIWFhcXHAkJYHZrYGZsaXpgd3BxZGBjemRoYWZ6ZGhhcQ==") b)))

;; Install TDMA and VSAT-PSTN technology license
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "VSAT_PSTN_FEATURE_LICENSE")(setBeanProperty b "Desc" "License for VSAT Technology")(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit")))  b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "QktHSV1fBwAcGx8SEBwfXx4BMAMDMl9NXFMAHRIWEU9fXx1fQ19CX0JfQ0FfCl9EQ0tGRERHRktFQENBREBAQUFKXwoUHB8cHRsQFidTJzIgJVMBHBVTFgAdFhAaP182ID02MDo/LDYhJicyNjUsPScgIywnMiAl") b)))


;;PREPAID_GROUP_POOLED_LICENSE_KEY
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "PREPAID_GROUP_POOLED_LICENSE_KEY")(setBeanProperty b "Desc" "Enable ability to create an account with AccountType=pooled and BillingType=prepaid.  If the license is not available, this combination of Account Type & Billing Type is not allowed to be selected.")(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit")))  b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "eTUzOTsvLXhkbXN0bmZgLWxzQnFxQC0/LiFyb2BkYz0tLW8tMS0wLTAtMTMteC02MTk0NjY1NDk3MjEzNjIyMzM4LS1YREpeRFJPREJITV5FRE1OTlFeUVROU0ZeRUhAUURTUQ==") b)))

;; Install non-individual license
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "NON_INDIVIDUAL_ACCOUNT_TYPE_LICENSE_KEY")(setBeanProperty b "Desc" "Allows account types to be created/updated as non-individual.")(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit")))  b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "YS8sLyM3NW1qdnF1eHp2dTV0a1ppaVg1JzY5and4fHslNTV3NSk1KDUoNSkrNWA1LikhLC4uLSwhLyopKy4qKisrIDU3fXxteHxrejl8ezl2bTlqfGlgbTltd2x2enp4OXV4bH1wb3B9d3A0d3Z3OWpudnV1WDVAXFJGXEpXXFpQVUZcSUBNRk1XTFZaWlhGVVhMXVBPUF1XUEZXVlc=") b)))


;; AIRTIME Subscription Type Enum
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "AIRTIME_SUBSCRIPTION_TYPE")(setBeanProperty b "Desc" "Allows the use of \"Airtime\" subscriptions.")(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit")))  b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "") b)))

;; MOBILE WALLET Subscription Type Enum
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "MOBILE_WALLET_SUBSCRIPTION_TYPE")(setBeanProperty b "Desc" "Allows the use of \"Mobile Wallet\" subscriptions.")(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit")))  b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "") b)))

;; NETWORK WALLET Subscription Type Enum
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "NETWORK_WALLET_SUBSCRIPTION_TYPE")(setBeanProperty b "Desc" "Allows the use of \"Network Wallet\" subscriptions.")(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit")))  b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "") b)))


;;Mobile Money report license

(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "MOBILE_MONEY_REPORT")(setBeanProperty b "Desc" "To allow the mobile money functionality and connection to the Invoice Server")(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit")))  b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "LG1jYm56eCAnOzw4NTc7OHg5JhckJBV4ant0Jzo1MTZoeHg6eGR4ZXhleGRmeC14Y2RsYWNjYGFsYmdkZmNnZ2ZmbXgmMSImMQd0MTc9OyI6HXQxPCB0OyB0Ojs9IDcxOjo7N3QwOjV0LSA9ODU6Oz0gNzohMnQtMTo7OXQxOD02Ozl0MTwgdCM7ODg1dDsAeAAGGwQRBgsNERobGQsRGB0WGxk=") b)))

;; Account Extension Licenses
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "com.redknee.app.crm.extension.account.FriendsAndFamilyExtension")(setBeanProperty b "Enabled" #f)(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit"))) (setBeanProperty b "Enabled" #f) b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "OnZ6dHhsbjsnLjA3LSUjbi8wATIyA258bWIxLCMnIH5ubixuLG51cnp3dXV2d3p0cXJwdXFxcHB7bm4sLSsxLCc2Ogc7LisvIwQmLAMxJiwnKzAEbCwtKzEsJzY6J2w2LDctISEjbC8wIWwyMiNsJycsKSYnMGwvLSE=") b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "com.redknee.app.crm.extension.account.GroupPricePlanExtension")(setBeanProperty b "Enabled" #f)(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit"))) (setBeanProperty b "Enabled" #f) b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "LmNnYWx4ei8zOiQjOTE3ejskFSYmF3poeXYlODczNGp6ejh6OHphZm5jYWFiY25gZWZkYWVlZGRveno4OT8lODMiLhM4NzoGMzU/JAYmIzkkEXg4OT8lODMiLjN4IjgjOTU1N3g7JDV4JiY3eDMzOD0yMyR4Ozk1") b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "com.redknee.app.crm.extension.account.SubscriberLimitExtension")(setBeanProperty b "Enabled" #f)(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit"))) (setBeanProperty b "Enabled" #f) b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "X1ZaVEBCFwsCHBsBCQ9CAxwtHh4vQlBBTh0ADwsMUkJCAEIAQlleVltZWVpbVlhdXlxZXV1cXFdCQgABBx0ACxoWKxoHAwciHAsMBxwNHQwbPUAAAQcdAAsaFgtAGgAbAQ0ND0ADHA1AHh4PQAsLAAUKCxxAAwEN") b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "com.redknee.app.crm.extension.account.PoolExtension")(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit"))) (setBeanProperty b "Enabled" #f) b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "MHB5enJmZDglLTwmKTwpOjw7PmQlOgs4OAlkdmdoOyYpLSp0ZGQmZCZkf3hwfX9/fH1wfnt4en97e3p6cWRkJichOyYtPDANJCcnGGYmJyE7Ji08MC1mPCY9JysrKWYlOitmODgpZi0tJiMsLTpmJScr") b)))

;; Subscription Extension Licenses
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "com.redknee.app.crm.extension.subscriber.DualBalanceSubExtension")(setBeanProperty b "Desc" "This should be enabled if CRM supports dual balance on URCS.")(setBeanProperty b "Enabled" #f)(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit")))  b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "YGVqaX1/JyA8Oz8yMDw/fz4hECMjEn9tfHMgPTI2MW9/fz1/Y39if2J/Y2F/Kn9kY2tmZGRnZmtlYGNhZGBgYWFqf30AEAEGcz08czYwPTI/MjFzPzImN3MgJyE8IyMmIHMeARBzNTpzNzY/MTI9NnM2MXM3PyY8OyBzIDo7B389PDogPTYnKxYxJgA2MD0yPzIRPzImF30hNjE6ITAgMSYgfT08OiA9NicrNn0+ITB9IyMyfTY2PTg3NiF9Pjww") b)))

;; SPID Extension Licenses
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "com.redknee.app.crm.extension.spid.NotificationMethodSpidExtension")(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit"))) (setBeanProperty b "Enabled" #f) b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "JSElLDg6YmV5fnp3dXl6OntkVWZmVzooOTZleHdzdCo6Ong6JjonOic6JiQ6bzohJi4jISEiIy4gJSYkISUlJCQvOjo=") b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "com.redknee.app.crm.extension.spid.DuplicateAccountDetectionSpidExtension")(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit"))) (setBeanProperty b "Enabled" #f) b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "ICgpIjY0bGt3cHR5e3d0NHVqW2hoWTQmNzhrdnl9eiQ0NHY0KDQpNCk0KCo0YTQvKCAtLy8sLSAuKygqLysrKiohNDQ=") b)))
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "com.redknee.app.crm.extension.spid.PricePlanSwitchLimitSpidExtension")(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit"))) (setBeanProperty b "Enabled" #f) b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "Pnd1cXxoajI1KS4qJyUpKmorNAU2NgdqeGlmNSgnIyR6amooaihqcXZ+c3FxcnN+cHV2dHF1dXR0f2oPFgdmCxQFZigpZjIvKy8qZi4lMi8xNWYoJyoWZiMlLzQWaigpLzUoIzI+AyIvNhUyLysvCi4lMi8xFSgnKhYjJS80FmgiLzY1aCgpLzUoIzI+I2grNCVoNjYnaCMjKC0iIzRoKykl") b)))

;; User Group Extension Licenses
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "com.redknee.app.crm.extension.usergroup.AdjustmentTypeLimitUserGroupExtension")(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit"))) (setBeanProperty b "Enabled" #f) b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "IiEiKT0/Z2B8e39ycHx/P35hUGNjUj8tPDNgfXJ2cS8/P30/Iz8iPyI/IyE/aj8kIysmJCQnJislICMhJCAgISEqPz8=") b)))

;; Install Multi Language license
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "Multi Language")(setBeanProperty b "Enabled" #f)(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit"))) b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "aCYnJio+PGRjf3h8cXN/fDx9YlNgYFE8Lj8wY35xdXIsPDx+PH48JyAoJScnJCUoJiMgIicjIyIiKTw8dXdxZXd+cVwweWR8ZV0=") b)))


;;Prepaid Calling Card License, Default Disabled
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "PREPAID_CALLING_CARD_LICENSE_KEY")(setBeanProperty b "Desc" "Prepaid calling card license")(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit")))  b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "WFJcUERGHhkFAgYLCQUGRgcYKRoaK0ZURUoZBAsPCFZGRgRGWkZbRltGWlhGE0ZdWlJfXV1eX1JcWVpYXVlZWFhTRg8ZBA8JAwZKDhgLCUoNBAMGBgsJSg4DCxoPGDpGMy8hNS85JC8pIyY1LjgrKTUtJCMmJispNS4jKzovODo=") b)))


;; WIRE line subscription type license, Default Disabled
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "WIRE_LINE_LICENSE_KEY")(setBeanProperty b "Desc" "Wire line license key ")(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit")))  b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "Zy4vJyUxM2tscHdzfnxwczNybVxvb14zITA/bHF+en0jMzNxMy8zLjMuMy8tM2YzKC8nKigoKyonKSwvLSgsLC0tJjM/Znp0P3pscXp8dnM/enF2cz96bXZIM0ZaVEBaTFFaXFZTQFpRVlNAWk1WSA==") b)))

;; Broadband subscription type license
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "BROADBAND_SUBSCRIPTION_TYPE")(setBeanProperty b "Desc" "Allows the use of \"Broadband\" subscriptions.")(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit"))) (setBeanProperty b "Enabled" #f) b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "GVJYWVtPTRgEDRMUDgYATQwTIhERIE1fTkESDwAEA11NTQ9ND01WUVlUVlZVVFlXUlFTVlJSU1NYTU8SDw4IFREIEwISAxQSQUMFDwADBQAOEyNDQQcOQQQSFEEECRVBEhYODQ0gTSQxODU+Ly4oNTEoMyIyIzQyPiUvICMlIC4zIw==") b)))

;; Alcatel SSC Service Type license
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "Alcatel SSC")(setBeanProperty b "Enabled" #f)(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit"))) (setBeanProperty b "Enabled" #f) b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "eDk1MjouLHllbHJ1b2dhLG1yQ3BwQSw+LyBzbmFlYjwsLG4sbiw3MDg1Nzc0NTg2MzAyNzMzMjI5LCxDU1MgbGV0YWNsQQ==") b)))

;; Blackberry Service Type license
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "BlackBerry Support in CRM")(setBeanProperty b "Enabled" #f)(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit"))) (setBeanProperty b "Enabled" #f) b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "eDk1MjouLHllbHJ1b2dhLG1yQ3BwQSw+LyBzbmFlYjwsLG4sbiw3MDg1Nzc0NTg2MzAyNzMzMjI5LCxDU1MgbGV0YWNsQQ==") b)))
;; Disable BlackBerry Parameter Tracking.  Disabled by default.  Not offered.
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "Disable BlackBerry Parameter Tracking")(setBeanProperty b "Desc" "License to disable tracking of extraneous parameters (i.e. MSISDN) in the RIM Provisioning Server.  By default, this license is not enabled, and CRM does track the extra (MSISDN) information in the Provisioning System.")(setBeanProperty b "Offered" #f)(setBeanProperty b "Enabled" #f)(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit")))  b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "XltSRkQcGwcABAkLBwREBRorGBgpRFZHSBsGCQ0KVEREBkRYRFlEWURYWkQRRF9YUF1fX1xdUF5bWFpfW1taWlFERgUNHBsRO0gPBgEGBwEbAR4HGjhIDQAcSAYBSAYHARwJBRoHDgYBSEEmLDshOyVASAkaHBANSA0AHEgDCwkaHEgbDQcMSCU6K0gMBglIRAwNBAoJBg1IHAcGSBsBSA0bBg0LAQRIGwEAHEhEHAQdCQ4NDEgRKkhIRhoNHhoNO0gPBgEGBwEbAR4HGjhIJSE6SA0AHEgGAUhBJiw7ITslSEYNRgFASBsaDRwNBQkaCRhIGx0HDQYJGhwQDUgOB0gPBgEDCwkaHEgNBAoJGwEMSAccSA0bBg0LASREDwYBAwsJGjxIGg0cDQUJGgk4SBEaGg0qAwsJBCpIDQQKCRsBLA==") b)))

;; PPSM Support
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "PPSM Support")(setBeanProperty b "Enabled" #t)(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit"))) (setBeanProperty b "Enabled" #t) b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "eDk1MjouLHllbHJ1b2dhLG1yQ3BwQSw+LyBzbmFlYjwsLG4sbiw3MDg1Nzc0NTg2MzAyNzMzMjI5LCxDU1MgbGV0YWNsQQ==") b)))

;; Advanced Features Menu Support license
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "Advanced Features Menu Support")(setBeanProperty b "Enabled" #t)(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit"))) (setBeanProperty b "Enabled" #f) b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "eDk1MjouLHllbHJ1b2dhLG1yQ3BwQSw+LyBzbmFlYjwsLG4sbiw3MDg1Nzc0NTg2MzAyNzMzMjI5LCxDU1MgbGV0YWNsQQ==") b)))

;; Late Fee Feature License
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "Late Fee Feature")(setBeanProperty b "Enabled" #f)(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit"))) (setBeanProperty b "Enabled" #f) b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "AwIFCx8dUFRTHVxDckFBcB0PHhFCX1BUUw0dHV8dAR0AHQAdAQMdSB0GAQkEBgYFBAkHAgEDBgICAwMIHR1UQ0RFUFR3EVRUdxFURVB9") b)))

;; Early Reward Feature License
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "Early Reward Feature")(setBeanProperty b "Enabled" #f)(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit"))) (setBeanProperty b "Enabled" #f) b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "BQsEBxMRXFhfEVBPfk1NfBEDEh1OU1xYXwEREVMRDREMEQwRDQ8RRBEKDQUICgoJCAULDg0PCg4ODw8EERFYT0hJXFh7HVlPXEpYbx1EUU9ceA==") b)))

;; Multi-SIM Feature License
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "Multi-SIM Feature")(setBeanProperty b "Enabled" #f)(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit"))) (setBeanProperty b "Enabled" #f) b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "BQsEBxMRXFhfEVBPfk1NfBEDEh1OU1xYXwEREVMRDREMEQwRDQ8RRBEKDQUICgoJCAULDg0PCg4ODw8EERFYT0hJXFh7HVlPXEpYbx1EUU9ceA==") b)))

;;SAP report
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "SAP_REPORT")(setBeanProperty b "Desc" "features to support SAP report")(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit")))  b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "Dg8MBxMRSU5SVVFcXlJREVBPfk1NfBEDEh1OU1xYXwEREVMRDREMEQwRDQ8RRBEKDQUICgoJCAULDg0PCg4ODw8EEUlPUk1YTx1tfG4dSU9STU1ITh1SSR1OWE9ISVxYWxFpb3JteG9ibXxu") b)))
;; GRR Developer License
(let ((ctx (getContext ctx "core"))) (homeCreateOrStore (.get ctx com.redknee.framework.license.LicenseHome.class) (let ((b (com.redknee.framework.license.License.))) (setBeanProperty b "Name" "GRR_Developer_License")(setBeanProperty b "Desc" "GRR Developer")(setBeanProperty b "Enabled" #f)(setBeanProperty b "RateLimit" (let ((b (getBeanProperty b "rateLimit")))  b))(setBeanProperty b "Expiry" (DateUtil.parse ""))(setBeanProperty b "Permissions" (let ((c (java.util.ArrayList.)))  c))(setBeanProperty b "Key" "UFtRWExOFhENCg4DAQ0OTg8QIRISI05cTUIRDAMHAF5OTgxOUk5TTlNOUlBOG05VUlpXVVVWV1pUUVJQVVFRUFBbThAHEg0OBxQHJkIwMCVOBxEMBwELLj0QBxINDgcUByY9MDAl") b)))

