;; note type
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (bindHome ctx com.redknee.app.crm.bean.NoteTypeHome.class com.redknee.app.crm.bean.NoteType.class)))
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.NoteTypeHome.class) (let ((b (com.redknee.app.crm.bean.NoteType.))) (setBeanProperty b "Type" "Suspended")(setBeanProperty b "Reasons" (let ((c (java.util.ArrayList.)))  c)) b))))
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.NoteTypeHome.class) (let ((b (com.redknee.app.crm.bean.NoteType.))) (setBeanProperty b "Type" "Deactive")(setBeanProperty b "Reasons" (let ((c (java.util.ArrayList.)))  c)) b))))
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.NoteTypeHome.class) (let ((b (com.redknee.app.crm.bean.NoteType.))) (setBeanProperty b "Type" "Adjustment")(setBeanProperty b "Reasons" (let ((c (java.util.ArrayList.)))  c)) b))))

(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.NoteTypeHome.class) (let ((b (com.redknee.app.crm.bean.NoteType.))) (setBeanProperty b "Type" "Inactive")(setBeanProperty b "Reasons" (let ((c (java.util.ArrayList.)))  c)) b))))

(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.NoteTypeHome.class) (let ((b (com.redknee.app.crm.bean.NoteType.))) (setBeanProperty b "Type" "Events")(setBeanProperty b "Reasons" (let ((c (java.util.ArrayList.)))  c)) b))))
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.NoteTypeHome.class) (let ((b (com.redknee.app.crm.bean.NoteType.))) (setBeanProperty b "Type" "Recurring Charge")(setBeanProperty b "Reasons" (let ((c (java.util.ArrayList.)))  c)) b))))
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.NoteTypeHome.class) (let ((b (com.redknee.app.crm.bean.NoteType.))) (setBeanProperty b "Type" "Trouble Ticket")(setBeanProperty b "Reasons" (let ((c (java.util.ArrayList.)))  c)) b))))
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.NoteTypeHome.class) (let ((b (com.redknee.app.crm.bean.NoteType.))) (setBeanProperty b "Type" "Question/Info")(setBeanProperty b "Reasons" (let ((c (java.util.ArrayList.)))  c)) b))))
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.NoteTypeHome.class) (let ((b (com.redknee.app.crm.bean.NoteType.))) (setBeanProperty b "Type" "CSR/Adjustment")(setBeanProperty b "Reasons" (let ((c (java.util.ArrayList.)))  c)) b))))
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.NoteTypeHome.class) (let ((b (com.redknee.app.crm.bean.NoteType.))) (setBeanProperty b "Type" "Customer Dispute")(setBeanProperty b "Reasons" (let ((c (java.util.ArrayList.)))  c)) b))))
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.NoteTypeHome.class) (let ((b (com.redknee.app.crm.bean.NoteType.))) (setBeanProperty b "Type" "AcctStateTransition")(setBeanProperty b "Reasons" (let ((c (java.util.ArrayList.)))  c)) b))))
(let ((ctx (getContext ctx "core"))) (let ((ctx (getContext ctx "AppCrmCore"))) (homeCreateOrStore (.get ctx com.redknee.app.crm.bean.NoteTypeHome.class) (let ((b (com.redknee.app.crm.bean.NoteType.))) (setBeanProperty b "Type" "Promotion")(setBeanProperty b "Reasons" (let ((c (java.util.ArrayList.)))  c)) b))))
